
zone_system: 1

skim_dict_factory: NumpyArraySkimFactory
#skim_dict_factory: MemMapSkimFactory

# read cached skims (using numpy memmap) from output directory (memmap is faster than omx )
read_skim_cache: False
# write memmapped cached skims to output directory after reading from omx, for use in subsequent runs
write_skim_cache: False



# when checkpointing cache. also write a csv version of tvpb cache for tracing
# (writes csv file when writing/checkpointing cache (i.e. when cached changed) even if rebuild_tvpb_cache is False)
# (n.b. csv file could be quite large if cache is STATIC!)
trace_tvpb_cache_as_csv: False

taz_skims: 
  - skims*.omx


skim_time_periods:
    time_window: 1440
    period_minutes: 30
    # periods: [0, 17, 48]
    # labels: &skim_time_period_labels ['AM', 'PM']
    periods: [0, 11, 17, 30, 37, 48]
    labels: &skim_time_period_labels ['EA', 'AM', 'MD', 'PM', 'EV']


